# Use postgres/example user/password credentials
version: '3.1'

services:
  angular-frontend:
    container_name: angular-frontend
    build: ./frontend/
    ports:
      - "8000:80"


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 
      POSTGRES_PASSWORD: example
