# Use postgres/example user/password credentials
version: '3.1'

services:
  angular-frontend:
    container_name: angular-frontend
    build: ./frontend/
    ports:
      - 8000:80
  express-backend:
    container_name: express-backend
    build: ./backend/
    ports: 
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=mydm
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_USER=johndoe
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080